# 主题设置
theme: jekyll-theme-hacker

# 网站信息
title: 我的黑客笔记
description: 自动更新目录的黑客风格笔记。

# Jekyll 插件 (推荐添加)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-relative-links # 处理相对链接

# Markdown 处理器
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# 排除不需要 Jekyll 处理的文件/文件夹
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - node_modules/
  - .github/ # 通常排除
# 注意：我们不在这里排除 README.md，因为要让主题处理它作为首页
